// Generated by https://quicktype.io

export interface IResult {
  data: IUser[] | IUser;
  support: ISupport;
  page?: number;
  per_page?: number;
  total?: number;
  total_pages?: number;
}

export interface IUser {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}

export interface ISupport {
  url: string;
  text: string;
}
